"""Constants for the Evri integration."""

DOMAIN = "evri"
CONF_API_KEY = "apiKey"
API_KEY = "RGVplG9He66OnnAjnGKz7Ovol9dKbSAr"
CONF_GET = "GET"
UNIQUE_ID_URL = "https://api.hermesworld.co.uk/enterprise-tracking-api/v1/parcels/search/{trackingNumber}"
TRACKING_INFO_URL = "https://api.hermesworld.co.uk/enterprise-tracking-api/v1/parcels/?uniqueIds={uniqueIds}&postcode={postCode}"
CONF_TRACK_A_PARCEL = "track_a_parcel"
CONF_TRACKING_NUMBER = "tracking_number"
CONF_POST_CODE = "postcode"
REQUEST_HEADERS = {"apiKey": "RGVplG9He66OnnAjnGKz7Ovol9dKbSAr"}
PARCEL_ITS_BOOKED = "0"
PARCEL_WERE_EXPECTING_IT = "1"
PARCEL_WEVE_GOT_IT = "2"
PARCEL_ON_ITS_WAY = "3"
PARCEL_ON_ITS_WAY_BACK = "4"
PARCEL_OUT_FOR_DELIVERY = "4_COURIER"
PARCEL_IS_DELIVERED = "5_COURIER"
PARCEL_UPDATE_ON_PARCEL = "6"
PARCEL_UPDATE_ON_PARCEL_INFO = "6_INFO"
PARCEL_CALL_TO_ACTION = "6_ACTION"
PARCEL_READY_FOR_COLLECTION = "4_SHOP"
PARCEL_COLLECTED = "5_SHOP"
PARCEL_RETURNED = "A"
PARCEL_DELIVERED = [PARCEL_IS_DELIVERED]
PARCEL_COLLECTION = [PARCEL_COLLECTED, PARCEL_READY_FOR_COLLECTION]
PARCEL_INFORMATION = [PARCEL_UPDATE_ON_PARCEL, PARCEL_UPDATE_ON_PARCEL_INFO]
PARCEL_IS_FINISHED = [PARCEL_IS_DELIVERED, PARCEL_COLLECTED, PARCEL_RETURNED]
PARCEL_DELIVERY_TODAY = [PARCEL_OUT_FOR_DELIVERY]
PARCEL_IN_TRANSIT = [
    PARCEL_ITS_BOOKED,
    PARCEL_WERE_EXPECTING_IT,
    PARCEL_WEVE_GOT_IT,
    PARCEL_ON_ITS_WAY,
    PARCEL_ON_ITS_WAY_BACK,
]
CONF_TRACKINGEVENTS = "trackingEvents"
CONF_TRACKINGSTAGE = "trackingStage"
CONF_TRACKINGPOINT = "trackingPoint"
CONF_TRACKINGSTAGECODE = "trackingStageCode"
CONF_DESCRIPTION = "description"
CONF_SENDER = "sender"
CONF_DISPLAYNAME = "displayName"
CONF_PARCELIDENTIFIERS = "parcelIdentifiers"
CONF_VALUE = "value"
CONF_PARCELS = "parcels"
CONF_RESULTS = "results"
CONF_DATETIME = "dateTime"
CONF_OUT_FOR_DELIVERY = "outForDelivery"
CONF_AVAILABLE_FOR_COLLECTION = "availableForCollection"
